### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by gadzhi** [ipoddubny/webcdr#15]
`
> webcdr@0.9.0 build /usr/src/webcdr
> browserify public/js/main.js -o public/js/build/bundle.js

Error: module not found: "audiojs" from file /usr/src/webcdr/public/js/plugins.js
    at onresolve (/usr/src/webcdr/node_modules/module-deps/index.js:180:30)
    at /usr/src/webcdr/node_modules/browserify/index.js:494:18
    at /usr/src/webcdr/node_modules/browser-resolve/index.js:247:21
    at /usr/src/webcdr/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/usr/src/webcdr/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/src/webcdr/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/src/webcdr/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webcdr@0.9.0 build: `browserify public/js/main.js -o public/js/build/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webcdr@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-08T09_20_14_774Z-debug.log

`

**Comment by gadzhi** [comment]
and when install bower install -allow root then
`bower bootstrap#~3.1.1          cached https://github.com/twbs/bootstrap.git#3.1.1
bower bootstrap#~3.1.1        validate 3.1.1 against https://github.com/twbs/bootstrap.git#~3.1.1
bower backgrid#~0.3.5           cached https://github.com/wyuenho/backgrid.git#0.3.8
bower backgrid#~0.3.5         validate 0.3.8 against https://github.com/wyuenho/backgrid.git#~0.3.5
bower backbone.paginator#~2.0.0 cached https://github.com/addyosmani/backbone.paginator.git#2.0.5
bower backbone.paginator#~2.0.0         validate 2.0.5 against https://github.com/addyosmani/backbone.paginator.git#~2.0.0
bower bootstrap-daterangepicker#~2.0.0    cached https://github.com/dangrossman/bootstrap-daterangepicker.git#2.0.14
bower bootstrap-daterangepicker#~2.0.0  validate 2.0.14 against https://github.com/dangrossman/bootstrap-daterangepicker.git#~2.0.0
bower backgrid-paginator#~0.3.5           cached https://github.com/wyuenho/backgrid-paginator.git#0.3.9
bower backgrid-paginator#~0.3.5         validate 0.3.9 against https://github.com/wyuenho/backgrid-paginator.git#~0.3.5
bower bootstrap-select#~1.5.2             cached https://github.com/silviomoreto/bootstrap-select.git#1.5.4
bower bootstrap-select#~1.5.2           validate 1.5.4 against https://github.com/silviomoreto/bootstrap-select.git#~1.5.2
bower audiojs#*                           cached https://github.com/kolber/audiojs.git#1.0.1
bower audiojs#*                         validate 1.0.1 against https://github.com/kolber/audiojs.git#*
bower font-awesome#~4.2.0                 cached https://github.com/FortAwesome/Font-Awesome.git#4.2.0
bower font-awesome#~4.2.0               validate 4.2.0 against https://github.com/FortAwesome/Font-Awesome.git#~4.2.0
bower                                  ENOTFOUND Package root not found
`

**Comment by bodnarbence** [comment]
hello, I have the same problem.
Did you find a solution? 

thank you.

**Comment by ipoddubny** [comment]
1. Change directory to `public` before running `bower install`.
2. The correct syntax for "allow root" is `bower install --allow-root`, with 2 dashes in front of "allow".

**Comment by bodnarbence** [comment]
Hello, 

thank you for your answer:
In this time I got this (the login page works well, after login, this happens):
Error: Pool is destroyed
    at Pool.acquire (/webcdr/node_modules/pool2/lib/pool.js:162:12)
    at /webcdr/node_modules/knex/lib/client.js:268:29
    at Promise._execute (/webcdr/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/webcdr/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/webcdr/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.acquireConnection (/webcdr/node_modules/knex/lib/client.js:264:21)
    at /webcdr/node_modules/knex/lib/runner.js:188:47
    at Promise._execute (/webcdr/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/webcdr/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/webcdr/node_modules/bluebird/js/release/promise.js:79:10)
    at /webcdr/node_modules/knex/lib/runner.js:187:35
    at tryCatcher (/webcdr/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/webcdr/node_modules/bluebird/js/release/method.js:39:29)
    at Runner.ensureConnection (/webcdr/node_modules/knex/lib/runner.js:186:39)
    at Runner.run (/webcdr/node_modules/knex/lib/runner.js:41:44)
    at QueryBuilder.Target.then (/webcdr/node_modules/knex/lib/interface.js:32:43)
    at QueryBuilder.tryCatcher (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
    at doThenable (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:52:38)
    at tryConvertToPromise (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/thenables.js:30:20)
    at Promise._resolveCallback (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:445:24)
    at Promise._settlePromiseFromHandler (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:518:17)
    at Promise._settlePromiseAt (/webcdr/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:584:18)
POST /login 500 9.008 ms - -

root@bence-test:/webcdr# lsb_release -r
Release:        16.04
root@bence-test:/webcdr# node -v
v4.2.6
root@bence-test:/webcdr# npm -v
3.5.2

Do you know the solution? 
Thank you!
