### ISSUE TITLE
server.js error

### ISSUE THREAD

**Issue by andycol** [ipoddubny/webcdr#9]
hi

i am runing debian 8
node version v0.10.29
node-v7.6.0

i get the error

/var/www/html/webcdr/server.js:93
const port = process.env.PORT || 9030;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by ipoddubny** [comment]
node.js 0.10 is not supported

**Comment by andycol** [comment]
will v6.10 work?
https://nodejs.org/en/download/
